# This is a basic workflow to help you get started with Actions

name: Build documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  simulink-images:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set up Matlab
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: latest
          products: Simulink
          cache: true

      - name: CLI matlab
      - run: sudo apt-get install xvfb
      - run: xvfb-run matlab -batch "addpath(genpath("Src")), exportSimulinkImages('Docs/source/simulink_images.json', 'Docs/source/simulink-images/');"


      # Run script
      - name: Run commands
        uses: matlab-actions/run-command@v2
        with:
          command: addpath(genpath("Src")), exportSimulinkImages('Docs/source/simulink_images.json', 'Docs/source/simulink-images/');
      
      # Store the images as an artifact for later use
      - name: Upload images as artifact
        uses: actions/upload-artifact@v4
        with:
          name: simulink-images
          path: Docs/source/simulink_images/
  
  sphinx-build:
    needs: simulink-images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Python and sphinx dependencies
      - uses: actions/setup-python@v3
      - name: Setup sphinx
        run: |
          pip install -r Docs/source/requirements.txt
      
      
      # Download images to folder Docs/source/simulin-images
      - name: Load simulink images
        uses: actions/download-artifact@v4
        with:
          name: simulink-images
          path: Docs/source

      - name: Sphinx build
        run: |
          sphinx-build Docs/source Docs/build
